### ISSUE TITLE
Streams not cleaned up in WaveRecorder when Exception occurs

### ISSUE THREAD

**Issue by walterg2** [NateRickard/Plugin.AudioRecorder#26] opened 2018-07-23 19:26 UTC
Problem Statement:
While using the AudioRecorder plugin, if a situation occurs where the `AudioStream` implementation throws an exception (the easiest one to replicate is to deny access to the Microphone), the `WaveRecorder` does not dispose of the `FileStream` and `BinaryWriter` objects. This makes it so you cannot clean up the directory and file that is requested the `wav` file to be saved to.

**Comment by NateRickard** [comment] 2018-08-10 20:01
@walterg2 I've released v1.0.2-pre where I attempted to handle this with some additional cleanup.  However, I can't reproduce the exception when I'm debugging... tried to decline the iOS mic prompt but it seems to allow me to continue to use the APIs w/o throwing errors.  Can you install and verify this release takes care of the issue you're seeing?

**Comment by NateRickard** [comment] 2018-08-22 17:14
Closing this issue but would be great if anyone could confirm this is fixed in the latest releases.

**Closed by NateRickard** 2018-08-22 17:14 UTC
